sudo: false
language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
notifications:
  email: alvaro@clustergy.com
before_install:
  - npm i -g npm@^4.0.0
before_script:
  - npm prune
script:
  - npm run test:staged
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release