sudo: false
language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
branches:
  only:
    - main
notifications:
  email: alvaro@clustergy.com
before_install:
  - npm i -g npm@^5.2.0
before_script:
  - npm prune
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npx semantic-release