sudo: false
language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
branches:
  only:
    - main
notifications:
  email: alvaro@clustergy.com
before_install:
  - npm i -g npm@^6.0.0
install: npm install
before_script:
  - npm prune
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
after_success:
  - npm run report-coverage
  - npm run semantic-release